id: splade_max-debug
title: 'SPLADE_max: SPLADEv2 with max aggregation'
parent: _common
gpu: true
base_hf_id: distilbert-base-uncased

indexation:
    requirements: duration=2 days & cpu(mem=2G)
    training_requirements: duration=4 days & cuda(mem=8G)
    max_docs: 20_000

validation:
    size: 10

splade:
    optimization:
        steps_per_epoch: 16
        batch_size: 16
        max_epochs: 4
        lr: 2.0e-5

    model: splade_max
    # validation for each (steps_per_epoch * validation interval) steps
    validation_interval: 2
    lambda_q: 3.0e-4
    lambda_d: 1.0e-4
    lambda_warmup_steps: 50000
    requirements: duration=4 days & cuda(mem=8G)

retrieval:
    requirements: duration=2 days & cuda(mem=8G)
    topK: 1000
    retTopK: 50
    batch_size_full_retriever: 200
